name: Continuous Integration

on:
  push:
    branches: [ dilekio-patch-1 ]
  pull_request:
    branches: [ dilekio-patch-1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
          env
          echo $GITHUB_WORKSPACE
